### ISSUE TITLE
(PEIFM) Farm life poops broken

### ISSUE THREAD

**Issue by SmeeSlug** [Craluminum2413/Craluminum-Mods#11]
Tested with just Farm life, PEI and IWPEIFEM, the poop items can't be used as fertiliser and don't show NPK values on the tool tip, they do work with only farmlife installed

**Comment by Craluminum2413** [comment]
I just fixed it, will be in 1.0.2 version

**Comment by Craluminum2413** [comment]
Released 1.0.2 version
