### ISSUE TITLE
Rope ladder block incorrect shape - Vanilla Variants (VanVar) 1.1.0 

### ISSUE THREAD

**Issue by linanohi** [Craluminum2413/Craluminum-Mods#4]
**Game Version:** v1.16.0-rc.2
**Mod Version:** 1.1.0 

**Description:**
Rope ladder, when placed, takes on the texture of basic wooden (oak) ladder instead of the rope ladder. The behaviour is unaffected and the ladder can still be picked up with RMB as it is with normal rope ladder.

No other mods installed. Tested with just Vanilla Variants, and confirmed that block appears correctly  without the mod installed.

**How to reproduce:**
1. Make a vanilla rope ladder
2. Place (sneak+LMB) on any vertical surface
3. Instead of rendering rope ladder block it renders vanilla wooden ladder instead

**Expected behavior:**
When placing rope ladder the block rendered should be the rope laddder, rather than vanilla wooden ladder

**Screenshots / Videos:**
<img width="499" alt="rope ladder incorrect block " src="https://user-images.githubusercontent.com/61794196/147411470-75f295d9-3c32-443f-bcdf-62d6e7ea30a2.png">

**Comment by Craluminum2413** [comment]
Thanks for the report, this is now fixed in 1.1.1
