### ISSUE TITLE
Beds missing rest hour values in Handbook / lower rest values than Vanilla - VanVar 1.1.1

### ISSUE THREAD

**Issue by linanohi** [Craluminum2413/Craluminum-Mods#5]
**Game Version:** v1.16.0-rc.7
**Mod Version:** v1.1.1

**Description:**
1. In Handbook all custom wood variants of beds are missing the number of hours of allowed rest (see screenshot)
2. VanVar beds only allow 6hrs of rest when placed (as opposed to Vanilla which allowes 8.5 (see screenshots)

**How to reproduce:**
1. View beds in Handbook
2. Place vanilla bed next to VanVar Bed to compare time allowed to rest in tooltip

**Expected behavior:**
Expecting 
1. visible number of allowed hours of sleep in the Handbook
2. the same amount of hours of rest allowed as the Vanilla bed... but if not maybe that could be added to the handbook recipe?

**Screenshots / Videos:**
<img width="328" alt="WalnutBed" src="https://user-images.githubusercontent.com/61794196/148587699-3a079855-c061-47b7-9471-81998af8a1b2.png">
<img width="292" alt="VanillaBed" src="https://user-images.githubusercontent.com/61794196/148587703-caec20b3-9148-46d6-b17b-5f4807f29575.png">
<img width="353" alt="VanillaBedHandbook" src="https://user-images.githubusercontent.com/61794196/148587717-bdb567ac-54a4-4a14-aa56-a8af7e903d2a.png">
<img width="301" alt="WalnutBedinHandbook" src="https://user-images.githubusercontent.com/61794196/148587718-d3fc18fd-7041-4f42-97c0-1326eeb252ed.png">

**Comment by Craluminum2413** [comment]
Fixed in 1.1.2
