### ISSUE TITLE
(MorePiles Quasi) Bowls are not crafted quasi bowls and vice versa

### ISSUE THREAD

**Issue by SmeeSlug** [Craluminum2413/Craluminum-Mods#8]
**Game Version:** 1.16.0.0
**Mod Version:** 1.0.0

**Description:**
The recipe to craft fired quasi bowls to normal ones and back doesn't work, and the quasi bowls cannot function as bowls (don't pick up fluids)

**How to reproduce:**
1. Make a quasi-bowl
2. Try to craft it into a regular bowl, or try to use it as a bowl
3. It doesn't do the thing.

Expected
Ability to craft quasi bowls and base game ones into each other.

**Comment by Craluminum2413** [comment]
Quasi bowls shouldn't hold liquids

**Comment by Craluminum2413** [comment]
Fixed in 1.0.1
