### ISSUE TITLE
(Wood Chests) Walnut Trunk only has 16 slots

### ISSUE THREAD

**Issue by lOmicronl** [Craluminum2413/Craluminum-Mods#9]
**Game Version:** 1.16.1
**Mod Version:** 1.0.1

**Description:**
All of the trunks have 36 slots. Except the walnut one. It only has 16.

**How to reproduce:**
1. Build or spawn a walnut trunk
2. Place it into the world
3. Open it and marvel

**Expected behavior:**
To get 36 storage slots when building a trunk.

**Comment by Craluminum2413** [comment]
Fixed in 1.0.2
